# Generated by Django 3.0.4 on 2020-04-07 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('officecode', models.IntegerField(primary_key=True, serialize=False)),
                ('officename', models.CharField(max_length=64)),
                ('attribution', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('officecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Office')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organizationcode', models.IntegerField(primary_key=True, serialize=False)),
                ('organizationname', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('datejoined', models.DateField()),
                ('address1', models.CharField(max_length=128)),
                ('address2', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('zipcode', models.IntegerField()),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('nativecountry', models.CharField(max_length=64)),
                ('citizenship', models.CharField(max_length=64)),
                ('isdelegate', models.CharField(max_length=64)),
                ('organizationcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('servicecode', models.IntegerField(primary_key=True, serialize=False)),
                ('servicename', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('premium', models.CharField(max_length=64)),
                ('allocation', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('subscriberID', models.IntegerField(primary_key=True, serialize=False)),
                ('requestdate', models.DateField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('motifofcancellation', models.CharField(max_length=64)),
                ('beneficiaryID', models.IntegerField()),
                ('servicecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Service')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('subscriptiontypecode', models.IntegerField(primary_key=True, serialize=False)),
                ('subscriptiontypename', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TransferredSubscription',
            fields=[
                ('transferID', models.IntegerField(primary_key=True, serialize=False)),
                ('transferfrom', models.CharField(max_length=64)),
                ('transferto', models.CharField(max_length=64)),
                ('requestdate', models.DateField()),
                ('transferdate', models.DateField()),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=64)),
                ('middlename', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('address1', models.CharField(max_length=128)),
                ('address2', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('zipcode', models.IntegerField()),
                ('employername', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscriptiontypecode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SubscriptionType'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserInfo'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='subscriberID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Subscriber'),
        ),
        migrations.AddField(
            model_name='officer',
            name='subscriberID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Subscriber'),
        ),
    ]
